name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # se ejecuta en cada push a main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js (opcional si luego usas frameworks)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Desplegar a GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
