name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # Se ejecuta en cada push a main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Validar HTML
        uses: chabad360/html-proofer@v1.0
        with:
          directory: ./

      - name: Desplegar a GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
